version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
    container_name: nestjs-api
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - nest-net

  cache:
    image: redis:6.2-alpine
    container_name: redis-cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
     - nest-net

volumes:
  cache:
    driver: local

networks:
  nest-net:
   driver: bridge